/// Need to pull all geodata. This is just a test.

var temp = 
{
"status": "OK",
"copyright": "Copyright (c) 2014 The New York Times Company.  All Rights Reserved.",
"num_results": 328,
"source_database": "slave",
"results": [
{
"concept_id": 4429,
"geocode_id": 16,
"concept_name": "Iraq",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 16,
"geoname_id": 99237,
"name": "Iraq",
"latitude": 33,
"longitude": 44,
"elevation": null,
"population": 28221000,
"country_code": "IQ",
"country_name": "Iraq",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Baghdad",
"dst_offset": 3,
"gmt_offset": 3,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 5485,
"geocode_id": 18,
"concept_name": "United States",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 18,
"geoname_id": 6252001,
"name": "US",
"latitude": 39.76,
"longitude": -98.5,
"elevation": null,
"population": 303824000,
"country_code": "US",
"country_name": "United States",
"admin_code1": "00",
"admin_code2": "089",
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": "US.00.089",
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "America/North_Dakota/New_Salem",
"dst_offset": -5,
"gmt_offset": -6,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 3926,
"geocode_id": 21,
"concept_name": "China",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 21,
"geoname_id": 1814991,
"name": "China",
"latitude": 35,
"longitude": 105,
"elevation": null,
"population": "1330044000",
"country_code": "CN",
"country_name": "China",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Chongqing",
"dst_offset": 8,
"gmt_offset": 8,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4440,
"geocode_id": 22,
"concept_name": "Israel",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 22,
"geoname_id": 294640,
"name": "Israel",
"latitude": 31.5,
"longitude": 34.75,
"elevation": null,
"population": 6500000,
"country_code": "IL",
"country_name": "Israel",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Jerusalem",
"dst_offset": 3,
"gmt_offset": 2,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 5171,
"geocode_id": 25,
"concept_name": "Russia",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 25,
"geoname_id": 2017370,
"name": "Russia",
"latitude": 60,
"longitude": 100,
"elevation": null,
"population": 140702000,
"country_code": "RU",
"country_name": "Russia",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Krasnoyarsk",
"dst_offset": 8,
"gmt_offset": 7,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 3503,
"geocode_id": 28,
"concept_name": "Afghanistan",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 28,
"geoname_id": 1149361,
"name": "Afghanistan",
"latitude": 33,
"longitude": 65,
"elevation": null,
"population": 32738000,
"country_code": "AF",
"country_name": "Afghanistan",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Kabul",
"dst_offset": 4.5,
"gmt_offset": 4.5,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4199,
"geocode_id": 29,
"concept_name": "France",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 29,
"geoname_id": 3017382,
"name": "France",
"latitude": 46,
"longitude": 2,
"elevation": null,
"population": 64094000,
"country_code": "FR",
"country_name": "France",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Europe/Paris",
"dst_offset": 2,
"gmt_offset": 1,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4284,
"geocode_id": 30,
"concept_name": "Great Britain",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 30,
"geoname_id": 2635167,
"name": "United Kingdom",
"latitude": 54,
"longitude": -4,
"elevation": null,
"population": 60943000,
"country_code": "GB",
"country_name": "United Kingdom",
"admin_code1": "00",
"admin_code2": "00",
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Europe/London",
"dst_offset": 1,
"gmt_offset": null,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4463,
"geocode_id": 31,
"concept_name": "Japan",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 31,
"geoname_id": 1861060,
"name": "Japan",
"latitude": 35.685356904338,
"longitude": 139.75308895111,
"elevation": null,
"population": 127288000,
"country_code": "JP",
"country_name": "Japan",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Tokyo",
"dst_offset": 9,
"gmt_offset": 9,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4428,
"geocode_id": 32,
"concept_name": "Iran",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 32,
"geoname_id": 130758,
"name": "Iran",
"latitude": 32,
"longitude": 53,
"elevation": null,
"population": 65875000,
"country_code": "IR",
"country_name": "Iran",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Tehran",
"dst_offset": 4.5,
"gmt_offset": 3.5,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4958,
"geocode_id": 33,
"concept_name": "Pakistan",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 33,
"geoname_id": 1168579,
"name": "Pakistan",
"latitude": 30,
"longitude": 70,
"elevation": null,
"population": 167762000,
"country_code": "PK",
"country_name": "Pakistan",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Karachi",
"dst_offset": 6,
"gmt_offset": 5,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4241,
"geocode_id": 35,
"concept_name": "Germany",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 35,
"geoname_id": 2921044,
"name": "Germany",
"latitude": 51.5,
"longitude": 10.5,
"elevation": null,
"population": 82369000,
"country_code": "DE",
"country_name": "Germany",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Europe/Berlin",
"dst_offset": 2,
"gmt_offset": 1,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4415,
"geocode_id": 37,
"concept_name": "India",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 37,
"geoname_id": 1269750,
"name": "India",
"latitude": 20,
"longitude": 77,
"elevation": null,
"population": "1147995000",
"country_code": "IN",
"country_name": "India",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Kolkata",
"dst_offset": 5.5,
"gmt_offset": 5.5,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4720,
"geocode_id": 39,
"concept_name": "Mexico",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 39,
"geoname_id": 3996063,
"name": "Mexico",
"latitude": 23,
"longitude": -102,
"elevation": null,
"population": 109955000,
"country_code": "MX",
"country_name": "Mexico",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "America/Monterrey",
"dst_offset": -5,
"gmt_offset": -6,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4443,
"geocode_id": 43,
"concept_name": "Italy",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 43,
"geoname_id": 3175395,
"name": "Italy",
"latitude": 42.8333333,
"longitude": 12.8333333,
"elevation": null,
"population": 58145000,
"country_code": "IT",
"country_name": "Italy",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Europe/Rome",
"dst_offset": 2,
"gmt_offset": 1,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 3833,
"geocode_id": 44,
"concept_name": "Canada",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 44,
"geoname_id": 6251999,
"name": "Canada",
"latitude": 60,
"longitude": -96,
"elevation": null,
"population": 33679000,
"country_code": "CA",
"country_name": "Canada",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "America/Rankin_Inlet",
"dst_offset": -5,
"gmt_offset": -6,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 4886,
"geocode_id": 47,
"concept_name": "North Korea",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 47,
"geoname_id": 1873107,
"name": "North Korea",
"latitude": 40,
"longitude": 127,
"elevation": null,
"population": 22912177,
"country_code": "KP",
"country_name": "North Korea",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Pyongyang",
"dst_offset": 9,
"gmt_offset": 9,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 5307,
"geocode_id": 49,
"concept_name": "South Korea",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 49,
"geoname_id": 1835841,
"name": "South Korea",
"latitude": 37,
"longitude": 127.5,
"elevation": null,
"population": 48422644,
"country_code": "KR",
"country_name": "South Korea",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Asia/Seoul",
"dst_offset": 9,
"gmt_offset": 9,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 3763,
"geocode_id": 50,
"concept_name": "Brazil",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 50,
"geoname_id": 3469034,
"name": "Brazil",
"latitude": -10,
"longitude": -55,
"elevation": null,
"population": 191908000,
"country_code": "BR",
"country_name": "Brazil",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "America/Cuiaba",
"dst_offset": -4,
"gmt_offset": -3,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
},
{
"concept_id": 5464,
"geocode_id": 53,
"concept_name": "Turkey",
"is_times_tag": 1,
"concept_type_id": 2,
"concept_status": "Active",
"concept_type": "nytd_geo",
"uri_prefix": "0",
"geocode": {
"geocode_id": 53,
"geoname_id": 298795,
"name": "Turkey",
"latitude": 39,
"longitude": 35,
"elevation": null,
"population": 71892000,
"country_code": "TR",
"country_name": "Turkey",
"admin_code1": "00",
"admin_code2": null,
"admin_code3": null,
"admin_code4": null,
"admin_name1": null,
"admin_name2": null,
"admin_name3": null,
"admin_name4": null,
"feature_class": "A",
"feature_class_name": "country, state, region,...",
"feature_code": "PCLI",
"feature_code_name": "independent political entity",
"time_zone_id": "Europe/Istanbul",
"dst_offset": 3,
"gmt_offset": 2,
"attributionName": "GeoNames",
"attributionUrl": "http://geonames.org"
}
}
]
}